# Site settings
title: Building Git2Go
email: info@git2go.com
description: > # this means to ignore newlines until "baseurl:"
  Git2Go is the first app for iOS which unleashes your full development productivity from everywhere.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://building.git2go.com" # the base hostname & protocol for your site
twitter_username: Git2Go
github_username:  nerdishbynature

# Build settings
markdown: kramdown
